```{r}
# limpio la memoria
rm(list = ls()) # remove all objects
gc() # garbage collection
```

```{r}
require("data.table")
require("rpart")
```

```{r}
# los parametros del script
#  deben copiarse a mano
PARAM <- list()

#-----------------------------
PARAM$experimento <- "salidas"

# puede ser { "ternaria", "binaria1", "binaria2" }
PARAM$clase <- "ternaria"

# poner 0 si no se quiere que se haga oversampling
PARAM$oversampling <- 0

# poner algo mayor a cero si se quiere cortar por probabilidad
#  generalmente debe ser 0.025 , si se quiere cortar por probabilidad
PARAM$prob_corte <-  0.025 #-1

# poner -1 si se quiere cortar por probabilidad
#  un numero mayor o igual a cero indica que se corta por cant envios
PARAM$corte <- -1 # 9248

# estos valores son simplemente de ejemplo
PARAM$rpart$cp <- -1
PARAM$rpart$minsplit <- 1733
PARAM$rpart$minbucket <- 378
PARAM$rpart$maxdepth <- 12
#-----------------------------

if( PARAM$prob_corte <= 0 & PARAM$corte <= 0 ) stop("debe elegir al menos una opcion de corte" )
if( PARAM$prob_corte > 0 & PARAM$corte > 0 ) stop("No puede elegir dos opcinoes de corte al mismo tiempo" )
if( PARAM$clase == "binaria2" & PARAM$corte <= 0 ) stop( "en el caso de clase binaria2  debe cortar por envios, PARAM$corte" )
```

```{r}
setwd("C:/Users/Usuario/Documents/P/M/dmeyf/fuente/")

# cargo el dataset
dataset <- fread("./datasets/competencia_01.csv")

dataset[, Visa_mlimitecompra := ifelse(is.na(Visa_mlimitecompra), 0, Visa_mlimitecompra)]
dataset[, Visa_mconsumosdolares := ifelse(is.na(Visa_mconsumosdolares), 0, Visa_mconsumosdolares)]

switch(PARAM$clase,
  "ternaria"  = dataset[, clase_nueva := ifelse( clase_ternaria=="BAJA+2", "POS", clase_ternaria ) ],
  "binaria1"  = dataset[, clase_nueva := ifelse( clase_ternaria=="BAJA+2", "POS", "NEG" ) ],
  "binaria2"  = dataset[, clase_nueva := ifelse( clase_ternaria %in% c( "BAJA+1","BAJA+2"), "POS", "NEG" ) ],
  stop(" PARAM$clase debe tener un valor valido")
)

# creo la carpeta donde va el experimento
#  HT  representa  Hiperparameter Tuning
dir.create("./exp/", showWarnings = FALSE)
dir.create( paste0("./exp/", PARAM$experimento, "/"),
           showWarnings = FALSE)
```


```{r}
dtrain <- dataset[foto_mes == 202103] # defino donde voy a entrenar
dapply <- dataset[foto_mes == 202105] # defino donde voy a aplicar el modelo
dapply[, clase_ternaria := NA ]

# hago el oversampling si hace falta
vector_pesos <- rep( 1.0, nrow(dtrain) )
if( PARAM$oversampling > 0 )   
  vector_pesos <- dtrain[, ifelse( clase_nueva=="POS", PARAM$oversampling, 1) ]
```


```{r}
# genero el modelo,  aqui se construye el arbol
modelo <- rpart(
        formula = "clase_nueva ~ . -clase_ternaria",
        data = dtrain, # los datos donde voy a entrenar
        xval = 0,
        control = PARAM$rpart,
        weights =  vector_pesos
)

# aplico el modelo a los datos nuevos
prediccion <- predict(
        object = modelo,
        newdata = dapply,
        type = "prob"
)
```

```{r}
# Establezco el Working Directory DEL EXPERIMENTO
setwd("C:/Users/Usuario/Documents/P/M/dmeyf/fuente/")
setwd( paste0("./exp/", PARAM$experimento, "/") )

# calculo en tablita lo necesario para generar el archivo prediccion
tablita <- dapply[, list(numero_de_cliente) ]
tablita[, prob := prediccion[, "POS"] ]
setorder( tablita, -prob )
tablita[, Predicted := 0L ]

if( PARAM$prob_corte > 0 ) {
  tablita[, Predicted := as.numeric(prob > PARAM$prob_corte)]
} else {
  if( PARAM$corte > 0 ) {
    #tablita[, Predicted := 0]
    tablita[ 1:PARAM$corte, Predicted := 1]
  }
}

# genero el submit para kaggle
nom_archivo <- paste0( PARAM$experimento, "_kaggle.csv" )

fwrite(tablita[, list(numero_de_cliente, Predicted)],
        file = nom_archivo,
        sep = ","
)
```

```{r}

```

