```{r}
rm(list = ls())
gc(verbose = FALSE)
```

```{r}
require("data.table")
require("rpart")
require("ROCR")
require("ggplot2")
require("caret")
```

```{r}
semillas <- c(886609, 201821, 623423, 105389, 151051)
```

```{r}
setwd("C:/Users/Usuario/Documents/P/M/dmeyf/fuente/")
dataset <- fread("./datasets/competencia_01.csv")
dataset <- dataset[foto_mes == 202103]
```

```{r}
dataset[, clase_binaria := ifelse(
                            clase_ternaria == "BAJA+2",
                                "evento",
                                "noevento"
                            )]
# Borramos el target viejo
dataset[, clase_ternaria := NULL]
```

```{r}
set.seed(semillas[1])
in_training <- caret::createDataPartition(dataset$clase_binaria,
                     p = 0.70, list = FALSE) 
dtrain  <-  dataset[in_training, ]
dtest   <-  dataset[-in_training, ]
```

```{r}
start_time <- Sys.time()
modelo <- rpart(clase_binaria ~ .,
                data = dtrain,
                xval = 0,
                cp = 0,
                minsplit = 20,
                minbucket = 1,
                maxdepth = 5)
print(Sys.time() - start_time)
```
```{r}
pred_testing <- predict(modelo, dtest, type = "prob")
head(pred_testing)
```
```{r}
# Armamos una función que nos calcule la ganancia, 
# usando el punto de corte de 0.025
ganancia <- function(probabilidades, clase) {
  return(sum(
    (probabilidades >= 0.025) * ifelse(clase == "evento", 273000, -7000))
  )
}

# La ganancia en testing NORMALIZADA
print(ganancia(pred_testing[, "evento"], dtest$clase_binaria) / 0.3)
```
```{r}
# Almacenaremos los resultados en una tabla
resultados_n_gan <- c()

# Calcule en función del tiempo de ejecución anterior, cuantos árboles puede
# hacer en 5 minutos y ponga ese número en la siguiente variable
n <- 83

set.seed(semillas[1])
t0 <- Sys.time()
for (i in 1:n) {
    in_training <- caret::createDataPartition(dataset[, get("clase_binaria")],
                            p = 0.70, list = FALSE)
    dtrain  <-  dataset[in_training, ]
    dtest   <-  dataset[-in_training, ]

    modelo <- rpart(clase_binaria ~ .,
                    data = dtrain,
                    xval = 0,
                    cp = 0,
                    minsplit = 20,
                    minbucket = 1,
                    maxdepth = 5)

    pred_testing <- predict(modelo, dtest, type = "prob")

    gan <- ganancia(pred_testing[, "evento"], dtest$clase_binaria) / 0.3

    resultados_n_gan <- c(resultados_n_gan, gan)
}
print(Sys.time() - t0)
```
```{r}
# La menor ganancia conseguida en test
print(min(resultados_n_gan))

# La mayor ganancia
print(max(resultados_n_gan))

# La media de la ganancia
print(mean(resultados_n_gan))

# Veamos la dispersión de la ganancia
ggplot() + aes(resultados_n_gan) + geom_density()
```
```{r}
# Veamos si tomar el promedio de 5 árboles nos ayuda a reducir la dispersión
cantidad_arboles <- 5

resultados_n_mcv <- c()
set.seed(semillas[1])

for (i in 1:50) 
    resultados_n_mcv <- c(resultados_n_mcv, mean(sample(resultados_n_gan, cantidad_arboles)))

# La menor ganancia conseguida en test
print(min(resultados_n_mcv))

# La mayor ganancia
print(max(resultados_n_mcv))

# La media de la ganancia
print(mean(resultados_n_mcv))

# Veamos la dispersión de la ganancia
ggplot() + aes(resultados_n_mcv) + geom_density()

```
```{r}
resultados_mis_semillas <- c()

t0 <- Sys.time()
for (s in semillas) {
    set.seed(s)
    in_training <- caret::createDataPartition(dataset[, get("clase_binaria")],
                            p = 0.70, list = FALSE)
    dtrain  <-  dataset[in_training, ]
    dtest   <-  dataset[-in_training, ]

    modelo <- rpart(clase_binaria ~ .,
                    data = dtrain,
                    xval = 0,
                    cp = 0,
                    minsplit = 20,
                    minbucket = 1,
                    maxdepth = 5)

    pred_testing <- predict(modelo, dtest, type = "prob")

    gan <- ganancia(pred_testing[, "evento"], dtest$clase_binaria) / 0.3

    resultados_mis_semillas <- c(resultados_mis_semillas, gan)

}
print(Sys.time() - t0)
```

```{r}
print(mean(resultados_mis_semillas))
```
```{r}
resultados_grid_search <- data.table()

for (cp in c(-1, 0.01)) { 
for (md in c(5, 10, 15, 30)) {
for (ms in c(1, 50, 500, 1000)) {
for (mb in c(1, as.integer(ms / 2))) {

    t0 <- Sys.time()
    gan_semillas <- c()
    for (s in semillas) {
        set.seed(s)
        in_training <- caret::createDataPartition(dataset[,
                        get("clase_binaria")],
                                p = 0.70, list = FALSE)
        dtrain  <-  dataset[in_training, ]
        dtest   <-  dataset[-in_training, ]

        modelo <- rpart(clase_binaria ~ .,
                        data = dtrain,
                        xval = 0,
                        cp = cp,
                        minsplit = ms,
                        minbucket = mb,
                        maxdepth = md)

        pred_testing <- predict(modelo, dtest, type = "prob")
        gan <- ganancia(pred_testing[, "evento"], dtest$clase_binaria) / 0.3

        gan_semillas <- c(gan_semillas, gan)
    }
    tiempo <-  as.numeric(Sys.time() - t0, units = "secs")

    resultados_grid_search <- rbindlist(list(
                                resultados_grid_search,
                                data.table(
                                    tiempo = tiempo,
                                    cp = cp,
                                    mb = mb,
                                    ms = ms,
                                    md = md,
                                    gan = mean(gan_semillas)) # se puede agregar el sd?
                                ))
}
}
}
}
```

```{r}
# Visualizo los parámetros de los mejores parámetros
print(resultados_grid_search[gan == max(gan), ])
```

```{r}
resultados_grid_search
```

