```{r}
rm(list = ls())
gc()
require("data.table")
require("rlist")
require("randomForest")
require("ggplot2")
```

```{r}
setwd("~/buckets/b1/")
DT <- fread("./datasets/competencia_02.csv.gz")
setorderv(DT, cols=c("foto_mes"), order=c(1L))
```

```{r}
unique(DT[["foto_mes"]])
```

```{r}
#meses = c(201908, 201909 ,201910, 201911, 201912, 202001, 202002, 202003 ,202004 ,202005,
#          202006, 202007, 202008 ,202009 ,202010, 202011 ,202012 ,202101 ,202102, 202103 ,202104 ,202105)

meses = c(202101, 202102, 202103, 202104, 202105)

DT_bajas = DT[(foto_mes %in% meses) & (clase_ternaria == "BAJA+2")]
ids = unique(DT_bajas[["numero_de_cliente"]])

DT_bajas_hist = DT[numero_de_cliente %in% ids]
setorderv(DT_bajas_hist, cols=c("foto_mes"), order=c(1L))

rm(ids)
```


Crear col "t_hasta_baja" en DT_bajas_hist:
```{r}
mapeo_baja = DT_bajas[, c("numero_de_cliente", "foto_mes")]
colnames(mapeo_baja)[colnames(mapeo_baja) == "foto_mes"] = "foto_mes_baja2"

DT_bajas_hist[mapeo_baja, foto_mes_baja2 := foto_mes_baja2, on="numero_de_cliente"]
DT_bajas_hist[, t_hasta_baja :=  (foto_mes_baja2 - foto_mes)]
DT_bajas_hist[, foto_mes_baja2 := NULL]
setorderv(DT_bajas_hist, cols=c("t_hasta_baja"), order=c(-1L))

DT_bajas_hist[ , t_hasta_baja := frankv(t_hasta_baja, order=1L), 
               by=numero_de_cliente]

rm(mapeo_baja)
```


Ejemplo "t_hasta_baja":
```{r}
DT_bajas[numero_de_cliente == 29677433, 
                c("numero_de_cliente", "foto_mes")]
```

```{r}
DT_bajas_hist[numero_de_cliente == 29677433, 
                c("numero_de_cliente", "foto_mes", "t_hasta_baja")]
```


Crear DT_bajas_arb:
```{r}
DT_bajas_arb = copy(DT_bajas)
cols_a_remover = c("foto_mes", "clase_ternaria", "numero_de_cliente")
DT_bajas_arb[, (cols_a_remover) := NULL]
rm(cols_a_remover)

if (FALSE)
{
  cols_a_remover = c("active_quarter", "cliente_vip", "internet",
                     "cliente_edad", "cliente_antiguedad",
                     "mrentabilidad_annual", "cproductos",
                     "tcuentas", "ccuenta_corriente",
                     "ccaja_ahorro", "ctarjeta_debito", "cdescubierto_preacordado",
                     "ctarjeta_debito_transacciones", "ctarjeta_visa_transacciones",
                     "ctarjeta_master_transacciones",
                     "cprestamos_personales", "cprestamos_prendarios", 
                     "cprestamos_hipotecarios", "cplazo_fijo",
                     "cinversion1", "cinversion2", "cseguro_vida",
                     "cpayroll_trx", "cpayroll2_trx", "ccuenta_debitos_automaticos",
                     "ctarjeta_visa_debitos_automaticos", "ctarjeta_master_debitos_automaticos",
                     "cpagodeservicios", "cpagomiscuentas", "ccajeros_propios_descuentos",
                     "ctarjeta_visa_descuentos", "ctarjeta_master_descuentos",
                     "ccomisiones_mantenimiento", "ccomisiones_otras", "cforex",
                     "cforex_buy", "cforex_sell", "ctransferencias_recibidas",
                     "ctransferencias_emitidas", "cextraccion_autoservicio",
                     "ccheques_depositados", "ccheques_emitidos",
                     "ccheques_depositados_rechazados", "ccheques_emitidos_rechazados",
                     "ccallcenter_transacciones",
                     "ccajas_transacciones", "ccajas_consultas",
                     "ccajas_depositos", "ccajas_extracciones",
                     "ccajas_otras", "catm_trx", "catm_trx_other",
                     "cmobile_app_trx",
                     "ctarjeta_visa", "ctarjeta_master",
                     "cseguro_auto", "cseguro_vivienda", "cseguro_accidentes_personales",
                     "ccaja_seguridad", "tcallcenter", "thomebanking",
                     "tmobile_app", "Master_delinquency",
                     "Master_status", "Visa_delinquency",
                     "Visa_status")
  DT_bajas_arb[, (cols_a_remover) := NULL]
  rm(cols_a_remover)
}


if (FALSE)  # eliminar NA
{
  contains_any_na = sapply(DT2, function(x) any(is.na(x)))
  cols_con_na = names(DT2)[contains_any_na]
  DT2[, (cols_con_na) := NULL]
} else {  # llenar NA
  DT_bajas_arb = na.roughfix(DT_bajas_arb)
}
```


```{r}
rf = randomForest::randomForest(x = DT_bajas_arb, y = NULL, 
                                ntree = 5000, 
                                proximity = TRUE,
                                oob.prox = TRUE,
                                type="unsupervised")
```

```{r}
rf_hc = hclust( as.dist(1 - rf$proximity), 
                method = "ward.D2" )
```

```{r}
rf_hc_corte <- cutree( rf_hc, 
                       k = 7 )
```

```{r}
table(rf_hc_corte)
```

```{r}
DT_bajas[ , cluster := as.factor(rf_hc_corte)]
mapeo_baja = DT_bajas[, c("numero_de_cliente", "cluster")]
DT_bajas_hist[mapeo_baja, cluster := cluster, on="numero_de_cliente"]
rm(mapeo_baja)
```

```{r}
table(DT_bajas_hist$cluster)
```

Gráficos:
```{r}
library(ggplot2)
setwd("~/buckets/b1/")
dir.create(paste0("./exp/", "clusters", "/"), showWarnings = FALSE)
setwd(paste0("./exp/", "clusters", "/"))

cols_a_graficar <- setdiff(
  colnames(DT_bajas_hist),
  c("numero_de_cliente", "foto_mes", 
    "clase_ternaria", "cluster", "t_hasta_baja")
)

pdf(file="clusters1.pdf")
for (col in cols_a_graficar)
{
   p <- ggplot(DT_bajas_hist, 
         aes( -t_hasta_baja, .data[[col]], 
              colour=as.factor(cluster) )) +
        #geom_point() +
        geom_smooth() +
        #ggtitle(paste0(col, "")) +
        xlab("t_hasta_baja") +
        ylab(paste0(col, "")) +
        labs(colour = "Cluster")
   print(p)
}
dev.off()

rm(cols_a_graficar)
```

```{r}
setwd("~/buckets/b1/")
dir.create(paste0("./exp/", "clusters", "/"), showWarnings = FALSE)
setwd(paste0("./exp/", "clusters", "/"))

pdf(file="clusters2.pdf")
cols_a_graficar = c("cliente_vip", "ccuenta_corriente", 
                    "mcuenta_corriente_adicional", "cprestamos_hipotecarios",
                    "mprestamos_hipotecarios", "mplazo_fijo_pesos",
                    "minversion1_dolares", "ccheques_emitidos_rechazados",
                    "mcheques_emitidos_rechazados", "Master_Finiciomora",
                    "Master_madelantopesos", "Master_madelantodolares",
                    "Master_cadelantosefectivo", "Visa_madelantopesos",
                    "Visa_madelantodolares", "Visa_cadelantosefectivo")
for (col in cols_a_graficar)
{
   p <- ggplot(DT_bajas_hist, 
         aes( -t_hasta_baja, .data[[col]], 
              colour=as.factor(cluster) )) +
        #geom_point() +
        geom_smooth(method="glm") +
        #ggtitle(paste0(col, "")) +
        xlab("t_hasta_baja") +
        ylab(paste0(col, "")) +
        labs(colour = "Cluster")
   print(p)
}
dev.off()

rm(cols_a_graficar)
```


```{r}
table( DT_bajas_hist$cliente_vip, useNA="always")
```

Ejemplo:
```{r}
nombre_col = "cliente_vip"

ggplot(DT_bajas_hist, 
       aes( x=-t_hasta_baja, y=.data[[nombre_col]],
            colour=as.factor(cluster))) +
  #geom_point() +
  geom_smooth(method="glm",
              method.args = list(family = binomial)) +
  xlab("t_hasta_baja") +
  ylab(paste0(nombre_col, "")) +
  labs(colour = "Cluster")
```






Otros:
```{r}
DTU = DT20[ , lapply(.SD, median) , by=c("cluster"), .SDcols=(nombres_cols_dt2) ]
mapeo_clusters = DT20[, c("numero_de_cliente", "cluster")]
```

```{r}
DTU
```

```{r}
DT3[mapeo_clusters, cluster := cluster, on="numero_de_cliente"]
```

```{r}
DTM = DT3[ , lapply(.SD, median) , by=c("cluster", "foto_mes"), .SDcols=sapply(DT3, is.numeric) ]
```

Evolución de variable (icol) para medianas de cada cluster: 
```{r, fig.width=10, fig.height=15}
library(ggplot2)
library(gridExtra)

colnm = "mactivos_margen"

plots = list()
for (iclust in 1:7)
{
  a = DTM[cluster == iclust,]
  b = a[, colnm, with=FALSE]
  b[, x := seq(1, nrow(a), by=1)]
  
  plots[[iclust]] <- ggplot(data=b, 
         aes(x=.data[["x"]], y=.data[[colnm]], group=1)) +
      geom_line(color="red") +
      geom_point() +
      ggtitle(paste0("Cluster ", iclust))
}

do.call(grid.arrange, c(plots, ncol=2) )
```
