```{r}
library(data.table)
library(zoo)
```

```{r}
a <- c(1, 2, 3, 4, 5, 6, 7, 8)
a
```

```{r}
shift(a, 2L, fill = NA, type="lag")
```

```{r}
set.seed(42)
DT <- data.table(x = rnorm(10), y = rlnorm(10), z = runif(10), g = c("a", "b"), key = "g")
DT
```

```{r}
campos_media <- c("y", "z")

for (i in 1:3)
{
  nuevas_cols = c()
  for(col in campos_media)
  {
    nuevas_cols = c(nuevas_cols, paste0(col, "_lag_", i))
  }
  DT[, (nuevas_cols) := shift(.SD, n=(i), fill=NA, type="lag"), 
                        .SDcols = (campos_media), by=(g)]
}
```


```{r}
cols_reemplazar_ceros = c("z", "y")
for (col in cols_reemplazar_ceros){
  DT[, (col) := fifelse( (g=="a") & (get(col) > 0.1),  
                         0.5 * (shift(get(col), n=1L, fill=NA, type="lag") + shift(get(col), n=1L, fill=NA, type="lead")), 
                                get(col))]
}
```

```{r}
DT
```



```{r}
DT[, paste0("ravg_", c("x", "y")) := lapply(.SD, rollmean, k = 3, na.pad = TRUE), 
   by = g, .SDcols = c("x", "y")]
DT
```

```{r}
DT <- data.table(ID=c('A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'C', 'C', 'C')
               , value_type =c('type 1', 'type 1','type 2','type 1','type 2','type 2','type 1','type 1','type 2','type 1','type 1','type 1')
               , value=c(1,4,7,2,3,5,1,6,8,2,2,3))
DT
```

```{r}
n <- 3L
DT[, roll_mean := {
        v <- if (.N - n >= 1L) c(seq.int(n), rep(n, .N-n)) else seq.int(min(n, .N))
        shift(frollmean(value, v, adaptive=TRUE))
    }, .(ID, value_type)]
DT
```

```{r}
DT <- data.table(ID=c('A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'C', 'C', 'C')
               , mes =c('202001','202002','202003','201912','202005', '202006',
                               '202001','202005','202003',
                               '202003','202001','202002')
               , value=c(1,4,7,2,3,5,1,6,8,2,2,3))
DT
```

```{r}
#DT <- DT[order(mes),]
setorderv(DT, cols=c("mes"), order=c(1L))
DT
```

```{r}
campos_media <- setdiff(
  colnames(DT),
  c("ID", "mes")
)

nuevas_cols = c()

for(col in campos_media)
{
  n <- 3L
  nueva_col = paste0(col, "_pmean", n)
  nuevas_cols = c(nuevas_cols, nueva_col)
  
  DT[, (nuevas_cols) := {
              v <- if (.N - n >= 1L) c(seq.int(n), rep(n, .N-n)) else seq.int(min(n, .N))
              shift(frollmean(.SD[[col]], v, adaptive=TRUE))
            }, by = ID]

  nueva_col = paste0(col, "_dif1")
  nuevas_cols = c(nuevas_cols, nueva_col)
  DT[, (nuevas_cols) := {
      c(NA, diff(.SD[[col]], lag=1, differences=1))
    }, .(ID)]

  nueva_col = paste0(col, "_dif2")
  nuevas_cols = c(nuevas_cols, nueva_col)
  DT[, (nuevas_cols) := {
      c(NA, NA, diff(.SD[[col]], lag=1, differences=2))
    }, .(ID)]
}
```

```{r}
DT
```

```{r}
for (col in c("value"))
{
  nueva_col = paste0(col, "_nrmr")
  DT[, (nueva_col) := round(rank(.SD[[col]])/.N, 5), by = "mes"]
  DT[, (col) := NULL]
}
```

```{r}
DT
```

```{r}
DT[, value2 := value +1]

n = 3
cols = c("value", "value2")
nuevas_cols = c()
for (col in cols)
{
  nuevas_cols = c(nuevas_cols, paste0(col, "_pmean_", n))
}

DT[, (nuevas_cols) := lapply(.SD, rollmean, k=(n), fill=NA, align="right"),  
                    .SDcols = (cols), by=ID]

DT[, (nuevas_cols) := lapply(.SD, shift, n=1L, fill=NA, type="lag"),  
                    .SDcols = (nuevas_cols), by=ID]


nuevas_cols = c()
for (col in cols)
{
  nuevas_cols = c(nuevas_cols, paste0(col, "_dif1"))
}
DT[, (nuevas_cols) := lapply(.SD, function(x) c(NA, diff(x, lag=1, differences=1))),
                    .SDcols = (cols), by=ID]
     
nuevas_cols = c()
for (col in cols)
{
  nuevas_cols = c(nuevas_cols, paste0(col, "_dif2"))
}
DT[, (nuevas_cols) := lapply(.SD, function(x) {
                        if (.N <= 2) rep(NA, .N) else
                        c(NA, NA, diff(x, lag=1, differences=2))
                      }),  
                    .SDcols = (cols), by=ID]

DT
```

```{r}
DT[, value2 := value +1]

n = 3
cols = c("value", "value2")
nuevas_cols = c()
for (col in cols)
{
  nuevas_cols = c(nuevas_cols, paste0(col, "_pmean_", n))
}

DT[, (nuevas_cols) := frollmean(.SD, n=(n), fill=NA, align="right", algo="fast"), 
                      .SDcols = (cols), by=ID]

DT[, (nuevas_cols) := shift(.SD, n=1L, fill=NA, type="lag"),
                      .SDcols = (nuevas_cols), by=ID] 

nuevas_cols = c()
for (col in cols)
{
  nuevas_cols = c(nuevas_cols, paste0(col, "_dif1"))
}

DT[, (nuevas_cols) := shift(.SD, n=1L, fill=NA, type="lag"), 
                        .SDcols = (cols), by=ID]

for (i in 1:length(cols))
{
  DT[, (nuevas_cols[i]) := DT[[cols[i]]] - DT[[nuevas_cols[i]]] ]
}

#DT[, (nuevas_cols) := .SD - shift(.SD, n=1L, fill=NA, type="lag"), 
#                        .SDcols = (cols), by=ID] 

#DT[, (nuevas_cols) := lapply(.SD, function(x) c(NA, diff(x, lag=1, differences=1))),
#                    .SDcols = (cols), by=ID]
     
nuevas_cols2 = c()
for (col in cols)
{
  nuevas_cols2 = c(nuevas_cols2, paste0(col, "_dif2"))
}

DT[, (nuevas_cols2) := shift(.SD, n=1L, fill=NA, type="lag"), 
                        .SDcols = (nuevas_cols), by=ID]

for (i in 1:length(cols))
{
  DT[, (nuevas_cols2[i]) := DT[[nuevas_cols[i]]] - DT[[nuevas_cols2[i]]] ]
}

#DT[, (nuevas_cols) := lapply(.SD, function(x) {
#                        if (.N <= 2) rep(NA, .N) else
#                        c(NA, NA, diff(x, lag=1, differences=2))
#                      }),  
#                    .SDcols = (cols), by=ID]

DT
```

```{r}
DT
```


```{r}
n <- 3L
DT[, prev_mean_3 := {
        v <- if (.N - n >= 1L) c(seq.int(n), rep(n, .N-n)) else seq.int(min(n, .N))
        shift(frollmean(value, v, adaptive=TRUE))
    }, by = (ID)]
DT
```

```{r}
n <- 3L

setorder(DT[, rn := .I], ID)
rid <- DT[, rowid(ID)]

DT[, roll_mean := shift(frollmean(value, n))]

ix <- DT[rid==3L, which=TRUE]
set(DT, ix, "roll_mean", DT[, shift(frollmean(value, n - 1L))][ix])

ix <- DT[rid==2L, which=TRUE]
set(DT, ix, "roll_mean", DT[, shift(value)][ix])

DT[rid==1L, roll_mean := NA_real_]
setorder(DT, rn)[]
DT[, rn:=NULL]
```



```{r}
DT[, value_diff1 := {
      c(NA, diff(value, lag=1, differences=1))
    }, .(ID)]
DT
```

```{r}
DT[, value_diff2 := {
      c(NA, NA, diff(value, lag=1, differences=2))
    }, .(ID)]
DT
```

```{r}
DT[, mes_rank := match(mes, sort(unique(mes))) ]
DT[, mes_prev_dif := {
        c(NA, diff(mes_rank, lag=1, differences=1))
    }, .(ID)]
DT
```

```{r}
#campos_nrm_rango = c("mes", "value")
#nuevas_cols = c()
#for(col in campos_nrm_rango)
#{
#  nuevas_cols = c(nuevas_cols, paste0(col, "_nrmr1"))
#}

#DT[, (nuevas_cols) := frank(.SD)/.N,
#                      .SDcols = (campos_nrm_rango), by=mes]

#DT[, (nuevas_cols) := frank(.SD),
#                      .SDcols = (campos_nrm_rango), by=mes]

#DT[, (nuevas_cols) := NULL]


DT[, value2 := value + 100]
campos_nrm_rango = c("value", "value2")
for (col in campos_nrm_rango)
{
  nueva_col = paste0(col, "_nrmr1")
  DT[, (nueva_col) := NULL]
  DT[get(col) == 5, (nueva_col) := 0]
  DT[get(col) > 5, (nueva_col) := frank(get(col)), by=mes]
  DT[get(col) < 5, (nueva_col) := -frankv(get(col), order=-1L), by=mes]
}

DT
```

```{r}
DT[get("value") < 5,]
```


```{r}
DT
```


```{r}
DT[, value_rnrm2 := round(rank(value)/.N, 5), by = mes]
DT
```

```{r}
DT[,col0 := 0.0]
DT
```
```{r}
DT[, col2 := "asd"]
DT[, col2 := NULL ]
```

```{r}
DT[mes %in% c(201912, 202005), col0 := NA ]
DT
```

```{r}
DT[, value_lag1 := {
        shift(value, 1L, fill = NA, type="lag")
    }, .(ID)]
DT
```

