```{r}
rm(list = ls())
gc()           

require("data.table")
require("rlist")
```

```{r}
PARAM <- list()
PARAM$finalmodel$optim$num_iterations <- 829
PARAM$finalmodel$optim$learning_rate <- 0.0314795407476228
PARAM$finalmodel$optim$feature_fraction <- 0.575871678909783
PARAM$finalmodel$optim$min_data_in_leaf <- 5336
PARAM$finalmodel$optim$num_leaves <- 478

#----------------------
# Hiperparametros FIJOS de  lightgbm
PARAM$finalmodel$lgb_basicos <- list(
  boosting = "gbdt", # puede ir  dart  , ni pruebe random_forest
  objective = "binary",
  metric = "custom",
  first_metric_only = TRUE,
  boost_from_average = TRUE,
  feature_pre_filter = FALSE,
  force_row_wise = TRUE, # para reducir warnings
  verbosity = -100,
  max_depth = -1L, # -1 significa no limitar,  por ahora lo dejo fijo
  min_gain_to_split = 0.0, # min_gain_to_split >= 0.0
  min_sum_hessian_in_leaf = 0.001, #  min_sum_hessian_in_leaf >= 0.0
  lambda_l1 = 0.0, # lambda_l1 >= 0.0
  lambda_l2 = 0.0, # lambda_l2 >= 0.0
  max_bin = 31L, # lo debo dejar fijo, no participa de la BO

  bagging_fraction = 1.0, # 0.0 < bagging_fraction <= 1.0
  pos_bagging_fraction = 1.0, # 0.0 < pos_bagging_fraction <= 1.0
  neg_bagging_fraction = 1.0, # 0.0 < neg_bagging_fraction <= 1.0
  is_unbalance = FALSE, #
  scale_pos_weight = 1.0, # scale_pos_weight > 0.0

  drop_rate = 0.1, # 0.0 < neg_bagging_fraction <= 1.0
  max_drop = 50, # <=0 means no limit
  skip_drop = 0.5, # 0.0 <= skip_drop <= 1.0

  extra_trees = TRUE, # Magic Sauce

  seed = 1
)

param_completo <- c(
  PARAM$finalmodel$lgb_basicos,
  PARAM$finalmodel$optim)
```


```{r}
s = 5
param_completo$seed = s
```


```{r}
cortes <- seq(3, 15, by = 2)
tb_f <- data.table(nenvios = cortes)
tb_f[, gan := 0]
```

```{r}
tb_entrega = data.table( clase_ternaria = sample(c("CONTINUA", "BAJA+1", "BAJA+2"), 
                         replace = TRUE, 100) )

for (envios in cortes) {
  tb_entrega[, Predicted := 0L]
  tb_entrega[1:envios, Predicted := 1L]
  
  tb_entrega[, gan := fifelse((Predicted == 1) & (clase_ternaria == "BAJA+2"),
                              273000, -7000)]
  
  tb_entrega[, gan_acum := cumsum(gan)]
  gan_tot = tb_entrega[envios, gan_acum]
  
  tb_f[nenvios == envios, gan := gan_tot]
}
```


```{r}
tb_f[, gan_suavizada :=
  frollmean(
    x = gan, n = 3, align = "center",
    na.rm = FALSE, hasNA = FALSE
  )]

gan_max_ <- tb_f[, max(gan_suavizada, na.rm = TRUE)]
pos_max_ <- which.max(tb_f[, gan_suavizada])
envios_max_ <- tb_f[pos_max_, nenvios]
```

```{r}
semillas = c(886609, 201821, 623423, 105389, 151051,
             978323, 594421, 797897, 911159, 892627)

tb_fs = data.table(semilla = semillas, 
                   gan_max = NA, 
                   envios_max = NA)
```

